In [1]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
import pandas as pd
import random
import os
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import math
from sklearn.multioutput import MultiOutputRegressor
import matplotlib.pyplot as plt # 득점모델 변수 중요도
import seaborn as sns
%matplotlib inline
from sklearn.decomposition import PCA

In [29]:
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
seed_everything(42) # Seed 고정

In [30]:
train_df = pd.read_csv('./train.csv')
train_df.drop([ 'X_02', 'X_48', 'X_47', 'X_23', 'X_11', 'X_10', 'X_04'], inplace= True, axis=1)

In [31]:
test_df = pd.read_csv('./test.csv')
test_df.drop([ 'X_02', 'X_48', 'X_47', 'X_23', 'X_11', 'X_10', 'X_04'], inplace= True, axis=1)

In [32]:
train_x = train_df.filter(regex='X') # Input : X Featrue
train_y = train_df.filter(regex='Y') # Output : Y_01 Feature..
test_x = test_df.filter(regex='X')
test_y = test_df.filter(regex='Y')

In [6]:
X_0506 = train_x[["X_01","X_05", "X_06"]]

train_x.drop(["X_01","X_05", "X_06"],axis=1,inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_12048\4133901488.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_x.drop(["X_01","X_05", "X_06"],axis=1,inplace=True)


In [33]:
train_x_pca = train_x.copy()

In [23]:
from sklearn.preprocessing import StandardScaler
X_0506 = StandardScaler().fit_transform(X_0506)
X_0506

array([[ 0.80271132, -0.81190089,  1.94079365],
       [ 0.4186678 , -0.71707028,  1.03805543],
       [ 1.57042184,  1.48774146,  1.03805543],
       ...,
       [ 0.03462428,  1.47132847, -0.76697848],
       [-0.73308623, -0.56935336, -1.21790507],
       [-0.73308623, -0.60765034, -0.31560937]])

In [87]:
from sklearn.preprocessing import StandardScaler
train_x_pca = StandardScaler().fit_transform(train_x_pca)
train_x_pca

test_x = StandardScaler().fit_transform(test_x)

In [89]:
columns = [f"{i+1}comp" for i in range(20)]


In [93]:
pca = PCA(n_components=20)
printcipalComponents = pca.fit_transform(test_x)
principalDf_test = pd.DataFrame(data=printcipalComponents, columns = [columns])

In [95]:
principalDf_test

1comp     2comp     3comp     4comp     5comp     6comp     7comp  \
0      4.436566  4.710954 -1.855503 -1.414837 -1.748719  2.164066  0.369192   
1     -0.779547  0.092615 -0.088363 -0.283825 -1.695752  4.253543 -0.745466   
2      3.508064  4.214491  4.784464  0.865462  4.392253  2.060011  1.043084   
3     -0.285359 -0.299613  3.318644 -0.615289  4.486654  0.797753  1.078411   
4      1.111183 -0.058474  0.445400 -1.229148  4.693326 -0.715815  2.432648   
...         ...       ...       ...       ...       ...       ...       ...   
39603  1.604237 -1.029964  1.031996  0.699881  1.305525 -2.055710 -0.408280   
39604 -0.365162 -3.257503  1.664414  2.262617  1.127567 -0.421384  0.798729   
39605  1.665671 -0.304092  1.984697  0.842646  1.706856 -1.563013 -0.471065   
39606  2.476032  0.188780  1.246322  1.450950  1.270004 -1.199476 -0.502526   
39607  1.384160 -1.035018 -1.187311  0.694574  2.472794 -0.457398 -0.301201   

          8comp     9comp    10comp    11comp    12comp    13comp    14comp  \
0     -2.800608  0.575261 -0.734410  0.157660  1.396420  0.537878 -0.307805   
1      0.147308 -0.994428 -0.619127 -0.403261 -0.060816 -2.538296 -0.098348   
2     -3.374774  2.979237  2.326346  0.264732  1.475042 -0.725043  1.286428   
3     -1.761645  1.199562  2.052726 -1.030580  0.883128  1.306684  0.266206   
4     -0.902155  2.671164  2.122978 -0.426695  1.509762 -0.846648  2.247473   
...         ...       ...       ...       ...       ...       ...       ...   
39603  0.616008  0.206361 -1.569305 -0.073917 -2.217954  3.757912  0.400607   
39604  0.466455 -0.616229 -2.436966 -0.150190 -1.746120  2.518842  1.810159   
39605 -0.111005  0.908237 -1.423499 -0.108108 -1.857655  1.725990  1.216999   
39606  0.984431 -0.113305 -1.374071 -0.304341 -1.847860  2.949078  1.051644   
39607  0.724199 -0.099481 -1.507481  0.428963 -1.421644  2.918066  0.469031   

         15comp    16comp    17comp    18comp    19comp    20comp  
0      0.327642 -0.745886 -0.635644 -0.237257 -0.567266  0.505395  
1      0.853662  0.548809 -2.120763 -0.037303 -0.274749  0.062189  
2      0.627961 -0.119840  1.080300 -1.238633 -0.560678 -0.629712  
3     -0.973037  0.849579  0.209249 -0.071391  0.274970  0.274636  
4     -0.643578 -0.179733  1.146332  0.558958 -0.183709 -0.148968  
...         ...       ...       ...       ...       ...       ...  
39603  3.048684  0.402167 -1.572520  1.360379 -0.475813  0.040478  
39604  4.174802  0.392215 -0.032047 -0.077307 -0.708214 -0.133525  
39605  3.439076 -1.745869 -1.329120  1.969393 -0.134444  0.941569  
39606  3.288950 -0.628003 -1.868932  0.495139 -0.539230 -0.714766  
39607  3.345360 -0.969190 -2.051597  0.721330 -0.634412  0.086095  

[39608 rows x 20 columns]

In [80]:
columns = [f"{i+1}comp" for i in range(20)]


In [81]:
pca = PCA(n_components=20)
printcipalComponents = pca.fit_transform(train_x_pca)
principalDf = pd.DataFrame(data=printcipalComponents, columns = [columns])

In [82]:
rf_run_Ro = RandomForestRegressor(random_state=0, max_depth=30, min_samples_leaf=16, n_estimators=200)
LR_Ro = MultiOutputRegressor(rf_run_Ro).fit(principalDf, train_y)

In [84]:
train_predict = LR_Ro.predict(principalDf)
print("RMSE':{}".format(math.sqrt(mean_squared_error(train_predict, train_y))))

RMSE':1.015100032629558


In [96]:
pred = LR_Ro.predict(principalDf_test)

In [85]:
submit = pd.read_csv('sample_submission.csv')

In [97]:
for idx, col in enumerate(submit.columns):
    if col=='ID':
        continue
    submit[col] = pred[:,idx-1]
print('Done.')

Done.


In [70]:
pca.explained_variance_ratio_

array([0.12433913, 0.09375041, 0.08831654, 0.07483545, 0.04751895,
       0.03933579, 0.03864118, 0.03679977, 0.02778849, 0.02609538])

In [71]:
sum(pca.explained_variance_ratio_)

0.597421081141726

In [72]:
pcscore = pca.transform(X_0506)

ValueError: X has 3 features, but PCA is expecting 49 features as input.

In [73]:
pca.explained_variance_

array([6.09277124, 4.59388623, 4.32761964, 3.6670295 , 2.3284872 ,
       1.92750241, 1.89346539, 1.8032344 , 1.36167019, 1.2787059 ])

In [98]:
submit.to_csv('./rfpca_20.csv', index=False)